- name: Create beacon custom testnet dir
  file:
    path: "{{beacon_host_dir}}/config"
    state: directory

- name: Configure beacon node custom testnet
  copy:
    src: "{{custom_testnet_prysm_config}}"
    dest: "{{beacon_host_dir}}/config/prysm_config.yaml"
