- name: Create validator custom testnet dir
  file:
    path: "{{validator_host_dir}}/config"
    state: directory

- name: Configure validator node custom testnet
  copy:
    src: "{{custom_testnet_prysm_config}}"
    dest: "{{validator_host_dir}}/config/prysm_config.yaml"
