# hack to get different common defaults loaded, regardless of the choice of client-specific defaults

- name: include eth2stats defaults
  import_role:
    name: beacon_node
    defaults_from: 'eth2stats'
    tasks_from: noop

- name: include common defaults
  import_role:
    name: beacon_node
    defaults_from: 'main'
    tasks_from: noop

