- name: Prysm data files
  shell: |
    mv {{ input_data_dir }}/prysm/wallets {{ output_data_dir }}/selected/wallets
    mv {{ input_data_dir }}/prysm/keymanager_opts.json {{ output_data_dir }}/selected/keymanager_opts.json
