- name: Prysm data files
  delegate_to: localhost
  shell: |
    mv {{ input_data_dir }}/prysm/wallets {{ output_data_dir }}/wallets
    mv {{ input_data_dir }}/prysm/keymanager_opts.json {{ output_data_dir }}/keymanager_opts.json
