- name: Teku data files
  shell: |
    mv {{ input_data_dir }}/teku_validators_config.yaml {{ output_data_dir }}/selected/{{validators_config_file}}
    mv {{ input_data_dir }}/keys {{ output_data_dir }}/selected/keys
    mv {{ input_data_dir }}/secrets {{ output_data_dir }}/selected/secrets
