# Change me to something non-0 to run validators
validator_count_per_host: 0

validator_host: "host_{{inventory_hostname}}"
local_data_dir: "./wallets/{{eth2_network_name}}"
assignments_file: "{{local_data_dir}}/validator_assignments.json"
remote_out_data_dir: "{{local_data_dir}}/remote_{{validator_host|replace('.','_')}}"
remote_out_data_archive: "{{remote_out_data_dir}}.tar.gz"

# Change this to lighthouse, prysm, etc.
eth2client_name: foobar


validators_source_max: "{{lookup('env', 'SOURCE_WALLET_MIN')}}"
validators_source_min: "{{lookup('env', 'SOURCE_WALLET_MAX')}}"

eth2_fork_version: "0x00000123"
deposit_amount_gwei: "32000000000"

# Warning: this is testnet-quality, not so secure!
validators_source_mnemonic: "{{lookup('env', 'SOURCE_WALLET_VALIDATORS_MNEMONIC')}}"
withdrawals_source_mnemonic: "{{lookup('env', 'SOURCE_WALLET_WITHDRAWALS_MNEMONIC')}}"

assign_validators_wallet_name: "{{lookup('env', 'SOURCE_WALLET_NAME')}}"

deposit_datas_path: "/tmp/deposit_datas.txt"

# Change me to run a separate VC or not
has_validator_client: true

# When ethereal does not recognize the deposit contract address, it needs to be forced.
force_deposit: true

# E.g. "0x16e82D77882A663454Ef92806b7DeCa1D394810f"
deposit_contract_address: TODO change me

eth1_network_name: goerli
# Ethereal amount notation
deposit_actual_value: "32Ether"

# WARNING: not secure, only meant for quick testnet use
eth1_from_addr: "{{lookup('env', 'ETH1_FROM_ADDR')}}"
eth1_from_priv: "{{lookup('env', 'ETH1_FROM_PRIV')}}"

# List of strings, each a json encoded deposit data, with some misc. data (name, version) for ethereal cli.
deposit_datas: []
