eth2stats_enabled: true
eth2stats_host_dir: {{home_dir}}/eth2stats

eth2stats_container_name: eth2stats-client

eth2stats_require_restart: false
eth2stats_image_name: alethio/eth2stats-client:latest
eth2stats_addr: grpc.altona.eth2stats.io:443
eth2stats_display_name: Hello World
eth2stats_api_addr: localhost:4000
eth2stats_metrics_url: http://localhost:8080/metrics

# eth2stats_beacon_type: teku/nimbus/prysm/lighthouse/lodestar
