# Change this to "real_contract.hex" if you need to burn goerli eth and do something more like the real thing.
deposit_contract_file: "tdep_contract.hex"

deposit_contract_path: "{{role_path}}/files/{{deposit_contract_file}}"

deposit_contract_data: "{{lookup('file', deposit_contract_path)}}"

deposit_contract_network_name: goerli

# WARNING: not secure, only meant for quick testnet use
eth1_from_addr: "{{lookup('env', 'ETH1_FROM_ADDR')}}"
eth1_from_priv: "{{lookup('env', 'ETH1_FROM_PRIV')}}"
