---
- name: Show host vars
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - name: "Ansible | List all known variables and facts"
      debug:
        var: hostvars[inventory_hostname]
