---
- name: Start beacon node
  hosts:
    - beacon_node
  gather_facts: true
  tasks:
    - name: Setup node
      import_role:
        name: machine
        tasks_from: setup
      become: yes
    - name: Setup beacon node
      import_role:
        name: eth2client
        defaults_from: lighthouse
        tasks_from: start-beacon
